version: '3.8'

services:
  app:
    image: bytetopia/blankoblog:latest
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - ENV=development
      - DB_PATH=/app/data/blog.db

volumes:
  data: